apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: ${{ values.githubOwner }}/${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/kubernetes-id: ${{ values.name }}
  tags: [goldenpath, postgresql, dev]
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: goldenpath
