app:
  title: GoldenPath · Developer Platform
  baseUrl: http://localhost:3000
  packages: all
  extensions:
    - page:catalog:
        config: {path: /}
organization:
  name: GoldenPath · MATI
backend:
  baseUrl: http://localhost:7007
  listen: {port: 7007, host: 0.0.0.0}
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
permission:
  enabled: true
catalog:
  rules:
    - allow: [Component, System, Resource, API, Location, User, Group, Template]
  locations:
    - type: file
      target: ../../catalog/entities.yaml
    - type: file
      target: ../../templates/microservice/template.yaml
goldenpath:
  localMode: false
